import { describe, expect, it } from "vitest";
import {
  DMG_APP_XY,
  DMG_APPLICATIONS_XY,
  DMG_BACKGROUND_HEIGHT,
  DMG_BACKGROUND_PATH,
  DMG_BACKGROUND_PIXELS_PER_METER,
  DMG_BACKGROUND_WIDTH,
  dmgBackgroundDigest,
  encodeDmgBackgroundPng,
  renderDmgBackgroundRgb,
  runDmgBackgroundCli,
} from "../scripts/release/render-dmg-background.mjs";

function pixel(pixels: Buffer, x: number, y: number) {
  const offset = (y * DMG_BACKGROUND_WIDTH + x) * 3;
  return [pixels[offset], pixels[offset + 1], pixels[offset + 2]] as const;
}

describe("V2 DMG background renderer", () => {
  it("emits a deterministic 1320x800 RGB PNG at 144 DPI", () => {
    const first = encodeDmgBackgroundPng();
    const second = encodeDmgBackgroundPng();
    expect(DMG_BACKGROUND_WIDTH).toBe(1320);
    expect(DMG_BACKGROUND_HEIGHT).toBe(800);
    expect(DMG_BACKGROUND_PIXELS_PER_METER).toBe(5669);
    expect(DMG_BACKGROUND_PATH).toBe("src-tauri/icons/dmg-background.png");
    expect(Buffer.compare(first, second)).toBe(0);
    expect(first.subarray(0, 8)).toEqual(
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    );
    expect(first.toString("ascii", 12, 16)).toBe("IHDR");
    expect(first.readUInt32BE(16)).toBe(1320);
    expect(first.readUInt32BE(20)).toBe(800);
    expect(first[25]).toBe(2);
    const physStart = first.indexOf(Buffer.from("pHYs"));
    expect(first.readUInt32BE(physStart + 4)).toBe(5669);
    expect(first.readUInt32BE(physStart + 8)).toBe(5669);
    expect(first[physStart + 12]).toBe(1);
    expect(dmgBackgroundDigest(first)).toMatch(/^[0-9a-f]{64}$/u);
  });

  it("keeps wells empty of fake icons and draws the arrow between them", () => {
    const { pixels } = renderDmgBackgroundRgb();
    const app = pixel(pixels, DMG_APP_XY[0] * 2, DMG_APP_XY[1] * 2);
    const apps = pixel(
      pixels,
      DMG_APPLICATIONS_XY[0] * 2,
      DMG_APPLICATIONS_XY[1] * 2,
    );
    const arrow = pixel(pixels, 640, DMG_APP_XY[1] * 2);
    for (const well of [app, apps]) {
      expect(well[0]).toBeLessThan(180);
      expect(well[2]).toBeGreaterThan(well[0]);
    }
    expect(arrow[2]).toBeGreaterThan(200);
    expect(arrow[1]).toBeGreaterThan(arrow[0]);
  });

  it("matches the checked-in PNG", () => {
    expect(runDmgBackgroundCli(["--check"]).digest).toBe(dmgBackgroundDigest());
  });

  it("refuses unknown CLI flags and can check generated bytes", () => {
    expect(() => runDmgBackgroundCli(["--unknown"])).toThrow(
      "Usage: node scripts/release/render-dmg-background.mjs [--apply|--check]",
    );
    const png = encodeDmgBackgroundPng();
    const digest = dmgBackgroundDigest(png);
    expect(runDmgBackgroundCli([]).digest).toBe(digest);
    expect(
      runDmgBackgroundCli(["--check"], {
        writeFileSync() {
          throw new Error("check must not write");
        },
        readFileSync() {
          return png;
        },
      }).mode,
    ).toBe("check");
    expect(() =>
      runDmgBackgroundCli(["--check"], {
        writeFileSync() {
          throw new Error("check must not write");
        },
        readFileSync() {
          return Buffer.from("stale");
        },
      }),
    ).toThrow("does not match the deterministic V2 DMG renderer");
  });
});
