#ifndef FYAGENT_PRIVILEGED_BRIDGE_H
#define FYAGENT_PRIVILEGED_BRIDGE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum {
  FYAGENT_PRIVILEGED_ABI_VERSION = 1
};

enum {
  FYAGENT_PRIVILEGED_OPERATION_STATUS = 1,
  FYAGENT_PRIVILEGED_OPERATION_ENSURE_HELPER = 2,
  FYAGENT_PRIVILEGED_OPERATION_COMMIT = 3,
  FYAGENT_PRIVILEGED_OPERATION_REMOVE_HELPER = 4
};

enum {
  FYAGENT_PRIVILEGED_ACTION_NONE = 0,
  FYAGENT_PRIVILEGED_ACTION_FRESH_INSTALL = 1,
  FYAGENT_PRIVILEGED_ACTION_UPDATE_EXISTING = 2
};

enum {
  FYAGENT_PRIVILEGED_PRODUCT_CODEX_DESKTOP = 1,
  FYAGENT_PRIVILEGED_PRODUCT_OPENCODE_DESKTOP = 2,
  FYAGENT_PRIVILEGED_PRODUCT_QODERWORK = 3,
  FYAGENT_PRIVILEGED_PRODUCT_TRAEWORK = 4,
  FYAGENT_PRIVILEGED_PRODUCT_WORKBUDDY = 5
};

enum {
  FYAGENT_PRIVILEGED_OUTCOME_COMMITTED = 1,
  FYAGENT_PRIVILEGED_OUTCOME_ROLLBACK_RESTORED = 2,
  FYAGENT_PRIVILEGED_OUTCOME_RECOVERY_REQUIRED = 3,
  FYAGENT_PRIVILEGED_OUTCOME_READY = 4,
  FYAGENT_PRIVILEGED_OUTCOME_FAILED = 5
};

enum {
  FYAGENT_PRIVILEGED_HELPER_STATE_READY = 1,
  FYAGENT_PRIVILEGED_HELPER_STATE_UPDATE_REQUIRED = 2,
  FYAGENT_PRIVILEGED_HELPER_STATE_INCOMPATIBLE = 3,
  FYAGENT_PRIVILEGED_HELPER_STATE_RECOVERY_REQUIRED = 4,
  FYAGENT_PRIVILEGED_HELPER_STATE_MISSING = 5
};

enum {
  FYAGENT_PRIVILEGED_REASON_NONE = 0,
  FYAGENT_PRIVILEGED_REASON_HELPER_NOT_PACKAGED = 1,
  FYAGENT_PRIVILEGED_REASON_HELPER_SIGNATURE_INVALID = 2,
  FYAGENT_PRIVILEGED_REASON_HELPER_INSTALL_AUTHORIZATION_CANCELLED = 3,
  FYAGENT_PRIVILEGED_REASON_HELPER_INSTALL_FAILED = 4,
  FYAGENT_PRIVILEGED_REASON_HELPER_UPDATE_REQUIRED = 5,
  FYAGENT_PRIVILEGED_REASON_HELPER_DOWNGRADE_REJECTED = 6,
  FYAGENT_PRIVILEGED_REASON_HELPER_PROTOCOL_INCOMPATIBLE = 7,
  FYAGENT_PRIVILEGED_REASON_HELPER_PEER_REJECTED = 8,
  FYAGENT_PRIVILEGED_REASON_OPERATION_AUTHORIZATION_CANCELLED = 9,
  FYAGENT_PRIVILEGED_REASON_OPERATION_AUTHORIZATION_INVALID = 10,
  FYAGENT_PRIVILEGED_REASON_SOURCE_CAPABILITY_INVALID = 11,
  FYAGENT_PRIVILEGED_REASON_SOURCE_CHANGED = 12,
  FYAGENT_PRIVILEGED_REASON_TARGET_SLOT_INVALID = 13,
  FYAGENT_PRIVILEGED_REASON_HELPER_REMOVAL_FAILED = 14,
  FYAGENT_PRIVILEGED_REASON_TARGET_CHANGED = 15,
  FYAGENT_PRIVILEGED_REASON_APPLICATION_RUNNING = 16,
  FYAGENT_PRIVILEGED_REASON_PERMISSION_DENIED = 17,
  FYAGENT_PRIVILEGED_REASON_COMMIT_FAILED = 18,
  FYAGENT_PRIVILEGED_REASON_ROLLBACK_RESTORED = 19,
  FYAGENT_PRIVILEGED_REASON_RECOVERY_REQUIRED = 20,
  FYAGENT_PRIVILEGED_REASON_UNEXPECTED_FIELD = 21,
  FYAGENT_PRIVILEGED_REASON_RESERVED_NONZERO = 22
};

typedef struct FyAgentPrivilegedRequest {
  uint32_t abi_version;
  uint32_t size;
  uint32_t protocol_version;
  uint32_t operation;          /* 1=status 2=ensure_helper 3=commit 4=remove_helper */
  uint32_t action;             /* 1=fresh_install 2=update_existing; 0 otherwise */
  uint32_t product;            /* frozen table */
  uint32_t target_slot;        /* frozen table */
  uint32_t reserved0;
  uint8_t  operation_id[16];   /* UUID bytes */
  uint8_t  expected_source_revision[32];
  uint8_t  expected_target_revision[32];
  int32_t  source_directory_fd; /* -1 when unused */
  uint32_t reserved1;
} FyAgentPrivilegedRequest;

typedef struct FyAgentPrivilegedReply {
  uint32_t abi_version;
  uint32_t size;
  uint32_t protocol_version;
  uint32_t outcome;            /* 1=committed 2=rollback_restored 3=recovery_required 4=ready 5=failed */
  uint32_t reason;             /* closed helper reason; 0=none */
  uint32_t helper_state;       /* 1=ready 2=update_required 3=incompatible 4=recovery_required 5=missing */
  uint32_t reserved0;
  uint8_t  operation_id[16];
} FyAgentPrivilegedReply;

int fyagent_privileged_invoke(
  const FyAgentPrivilegedRequest *request,
  FyAgentPrivilegedReply *reply
);

#ifdef __cplusplus
}
#endif

#endif /* FYAGENT_PRIVILEGED_BRIDGE_H */
